### ISSUE TITLE
Feature: Add option to ignore hidden files/folders in library

### ISSUE THREAD

**Issue by luigi311** [revenz/FileFlows#17]
In the library screen add a toggle to ignore hidden files/folders
ex the following should be ignored:
- .video.mkv
- .folder/video.mkv

**Comment by luigi311** [comment]
I tried using 
> ^(?!\.)[\w .-/]+\.(ts|mp4|mkv|avi|mpe|mpg|mov|mpv|flv|wmv|webm|avchd|h(\.)?26[45])$

on the library regex but that is still pulling in files/folders that start with a . even though when i test it on regex101.com on the .net(C#) setting it comes back with exactly what i want

> test.mkv
.test.mkv
.testing/testing.mkv
.692bc64/encode/00127.mkv
encode/00127.mkv
.folder/video.mkv

![image](https://user-images.githubusercontent.com/4695527/159573875-95fbc7ef-dcb1-4b88-988a-4c45303605db.png)

**Comment by revenz** [comment]
its because it uses the full path in the regex, since you may want to filter out some folders, for example, an _UNPACK folder.
so you would need to write the regex for a fullpath.   doing it with files not starting with . is pretty simple file and folders where the folder would appear in the middle of the path is fun.

so.... a simple boolean would be easier.. ill add it

**Comment by revenz** [comment]
![image](https://user-images.githubusercontent.com/958400/159648243-2124e149-41b6-432f-b3bc-07b8ac2918eb.png)
added.  
much easier adding the option that working out the regex :)
