### ISSUE TITLE
Video Scaler Codec Parameters

### ISSUE THREAD

**Issue by achurak** [revenz/FileFlows#21]
Hello,

Is there a way to set the Video Codec Parameters for the Video Scaler node? Is there a reason this option is exposed for the Encode node, but not this one? I'm converting all my tv series to hevc, but since most of it is being watched on tablets I don't need anything higher than 720p, so I'm scaling everything as well, but would like to preserve the quality as much as possible (~CRF 20-21 potentially).
I know I can technically use the FFMPEG node, but would prefer to use the built-in one especially since this option is available for another, very similar, node.

Thanks!

**Comment by revenz** [comment]
![image](https://user-images.githubusercontent.com/958400/160784227-1e9a3110-ad53-4413-aaf4-192b20c38db7.png)
![image](https://user-images.githubusercontent.com/958400/160784320-4eefb64a-6b59-45db-bca0-07b7ddb6c401.png)
![image](https://user-images.githubusercontent.com/958400/160784375-5ba0cfda-0b0e-4c4a-a75d-937e05918995.png)


Implemented.   Also finally added the ability for nodes to hide properties based on values.  So you can see there "Video Codec Parameters" is only shown when "Custom" is set.

The "Force" option will skip a resolution sanity check (has to be + or - 60 pixels from the target to be considered the same resolution, except 480 is 40 pixels).

This requires a new FileFlows build due to the conditional arguments, so will be in the next release.
