### ISSUE TITLE
[Request] Add some way to delete empty directories

### ISSUE THREAD

**Issue by TuRDMaN** [revenz/FileFlows#384]
I am new to FileFlows, and was looking for a way to delete empty directories.

Someone was asking about this on Discord, and they were asked to create a ticket. I didn't see anything here, so I am doing it now.

It would be nice to have a function available for flows that would take a folder as an input, and then return either true if it is empty, or false if it contains anything, and then that folder could be passed along to a delete function.

Or, however you decide is the best way to implement it. I'd just like some way to purge empty folders from a library.

Thanks!

**Comment by revenz** [comment]
You can do this already, by using the "Folders" setting of the LIbrary.  When using this setting, a folder is sent through a flow instead of files within the folders.

https://docs.fileflows.com/libraries

You could then use a function node to detect if there are any files within the folder, and if not, deleted as required.
