### ISSUE TITLE
Build Documentation

### ISSUE THREAD

**Issue by reavessm** [revenz/FileFlows#44]
I was trying to make a PR to clean up some of the Dockerfiles (a few leave some lsiobase files) but I'm having a hard time building this on Linux.  Can you provide a quick list of steps that you use to build this so I send some PRs?  Even if you build on Windows, I don't mind trying to port it.  Once the build docs are done, I don't mind fleshing out some of the Linux edge cases or even adding more docs.

**Comment by revenz** [comment]
1.  Run build/build.ps1

done.

**Comment by revenz** [comment]
I should eloborate.  

The build scripts are designed for a windows environment and to be built by teamcity.   this is how the app is built and deployed.

the build scripts are therefore powershell scripts as they are designed for windows.  

The reason for windows is the windows installer only can be built on windows.   I have briefly looked at alternative installers that could be built on linux but havent found one yet.   Inno is a no go as that is flagged as a virus by windows more often than not.   nsis i need to investigate more.  The current wix based installer cannot be run on linux without wine, which is something i do not want to have to use.  I dont need to run the installers, i just need to build them on linux.

I have also considered removing the windows installer and just providing a zip, however, this makes it more complicated for the end user and the comlexity i feel is better left on the developer side of things.   So that is a no go.

I have considered moving the bulk of the build into a docker and have started experimenting with this, I just havent had the time to complete this.

I have also considered removing the ps1 scripts completely (powershell is an ugly language) and create a C# build script, since it needs dotnet anyway this is a feasible option.     Similar to cake scripts, but with .net 6, cake scripts themselves have become kinda pointless and you can achieve better results with pure C# now.   This is how I build stuff at my fulltime job and works very well.
I will very likely do this, and very likely very soon.   Then the build would be something along the lines of 

````
dotnet run
```
inside the build directory.

**Comment by revenz** [comment]
https://github.com/revenz/FileFlows/issues/45
New ticket to track that.  I'll see if I can finish this in the weekend.
