### ISSUE TITLE
Intel Quicksync (QSV) how to tell if being used?

### ISSUE THREAD

**Issue by iamwoz** [revenz/FileFlows#76]
My test flow just removes all non-English subtitles from the file - not sure if this is something that can be accelerated by QSV but regardless is there an indicator that QSV is available and being used? Cheers!

Docker compose:

services:
  fileflows:
    image: revenz/fileflows
    container_name: fileflows
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - /mnt/app/appdata/fileflows:/app/Data
      - /mnt/app/appdata/fileflows/logs:/app/Logs
      - /mnt:/media  #optional
    ports:
      - 5000:5000
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

![image](https://user-images.githubusercontent.com/85816876/171076710-47ad2ba4-e9df-460e-9f56-2fc3329045a4.png)

**Comment by revenz** [comment]
since youre just removing subtitles, nothing for QSV to do to my knowledge, so wont be used by ffmpeg.  

If you try to use QSV eg, h264_qsv, it will test if the processing node can use that hardware encoding, using the command
```
ffmpeg -loglevel error -f lavfi -i color=black:s=1080x1080 -vframes 1 -an -c:v h264_qsv -f null -
```
if that has errors, it will fallback to libx264, if that command does not have errors, then it will use it.

It does the fallback test so if you have a distributed system and one processing node has a qsv encoder, another an nvidia encoder and another none.  if you use hardware encoding in the "FFMPEG Builder: Video Encode" node it will nvidia then intel then fall back to cpu.  If you use the "Video Encode" node and use "h265" or "h264" (magic codecs) it will try nvidia, qsv, amd, then fallback to CPU.
