### ISSUE TITLE
Idle FF consumes ~16% CPU time on my i5-11400

### ISSUE THREAD

**Issue by iamwoz** [revenz/FileFlows#93]
This prevents my CPU in my server from clocking down.

I run btop on a dedicated monitor next to me for my server so have become really familiar with FF idle CPU usage.

Have tried changing all libraries to SCAN to see if was result of dotnet equivalent of ionotify but no change in idle CPU usage. 

Disable all Flows, Libraries and Internal Node also has no change in idle CPU usage.

The idle CPU usage is very predictable so any changes will be easy for me to see improvements. Cheers!

![image](https://user-images.githubusercontent.com/85816876/172120748-586c495e-2911-4b5e-a281-2068f5e5538c.png)

![image](https://user-images.githubusercontent.com/85816876/172120761-e4ec901f-6375-4632-aa65-4db0ab767d81.png)

**Comment by iamwoz** [comment]
As of version 0.8.0 FF is now averaging 16.2% continuous CPU time on my i5-11400. 

I'll need to find a way to limit its cpu usage via docker for now as this is keeping my 24x7 server at high clock speed (even with Governor set to powersave.

**Comment by revenz** [comment]
Started to tweak the workers for 0.8.1, this maybe an ongoing thing though, with more and more settings being exposed to reduce CPU usage.   eg, I may have to expose settings to how often a node checks for a new file etc.

**Comment by iamwoz** [comment]
Happy to do some comparisons between builds.

You running under Windows @revenz? Seeing similar idle usage or is this weird Linux dotnet behaviour?

**Comment by iamwoz** [comment]
Maybe I need to do some reading 😀

https://www.mytechramblings.com/posts/profiling-a-net-app-with-dotnet-cli-diagnostic-tools/

**Comment by revenz** [comment]
the biggest things that were causing the usage was 
1. the library scanner.   it would constantly check the queue for files.   I've made this now so its a timer, and the timer is stopped when queue is empty and when an item is added, the timer is started again.   so if you're not using scanning on a library, and using file system events, this drastically reduces it
2. workers now run at set times instead of minutes/hours after the app starts.  so I've scheduled most stuff for 5am, i may expose these settings somewhere.  but things like temp file clean up, log file clean up, now run at 5am.
3. also I've added an option to log every request to the server, so you can see what is "waking" the server at times.

**Comment by revenz** [comment]
I need to figure out how to take the docker stats from glances and put it into grafana so I can easily see the usage of FF.   grafana is great, but boy is it a complicated thing to try figure out.

**Comment by iamwoz** [comment]
I found some good TUI (terminal user interface) tools for this sort of this from: https://github.com/rothgar/awesome-tuis#dashboards

My non-recording dashboard is https://github.com/aristocratos/btop

For recording and playing back I use https://github.com/facebookincubator/below

Another awesome index of docker-specific tools here: https://github.com/veggiemonk/awesome-docker

**Comment by iamwoz** [comment]
Fixed on 0.8.1

![Screenshot_7](https://user-images.githubusercontent.com/85816876/174232189-661b1299-6b6a-4848-a56e-eea2d84180cd.png)
